### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ryanaltvater** [koistya/gulp-csscomb#11]
I'm having the issue below and can't seem to get around it. I'm using a custom .csscomb.json file I built from the CSScomb website, but I don't think that has an impact on this issue because when I remove the file the issue still occurs. Seems to be an issue with the plugin itself. I'm surprised nobody else has seemed to have this issue, other than a couple links I found where 1 person had a similar issue and then Tony addressed it with a fix. If you could help shed some light on what I might be doing wrong or how it can be addressed that would be awesome. Thanks!

<pre>events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '0' of undefined
    at module.exports.process (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/lib/options/eof-newline.js:16:26)
    at /Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:189:13
    at Array.forEach (native)
    at processTree (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:188:19)
    at processString (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:415:16)
    at DestroyableTransform._transform (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/index.js:65:27)
    at DestroyableTransform.Transform._read (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)</pre>

**Issue** - https://github.com/csscomb/csscomb.js/issues/93
**Fix** - https://github.com/csscomb/csscomb.js/pull/109

**Comment by vaeum** [comment]
I hope the author will read the message and correct the error

**Comment by koistya** [comment]
Can you run it with a debugger and check what does it pass to `csscomb.processString()` method? You can put a breakpoint here: https://github.com/koistya/gulp-csscomb/blob/efec3a1c70ac307fdd04e62203f3d96c2ad2df98/index.js#L65

**Comment by vaeum** [comment]
hello, I do not understand much in java script, but I can provide the terminal posts

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '0' of undefined
  at [object Object].module.exports.process (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/lib/options/space-after-selector-delimiter.js:27:28)
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
  at Array.forEach (native)
  at processNode (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
  at Array.forEach (native)
  at processNode (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
  at Array.forEach (native)
  at processNode (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:189:13
  at Array.forEach (native)
  at processTree (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:188:19)
  at [object Object].processString (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:415:16)
  at DestroyableTransform._transform (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/index.js:65:27)
  at DestroyableTransform.Transform._read (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at evalmachine.<anonymous>:272:14
  at /Users/vaeum/Desktop/Project/new.page/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:108:15)
```
